FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /data

COPY otter /usr/local/bin/otter
RUN chmod +x /usr/local/bin/otter

ENTRYPOINT ["/usr/local/bin/otter"]
